### ISSUE TITLE
Rename Classes and Variables according to naming convention 

### ISSUE THREAD

**Issue by shobhitagarwal1612** [Software-Incubator/DirectMe-Android-Client#2]
Check out this link 
https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md
https://source.android.com/source/code-style.html

**Comment by shobhitgarg9536** [comment]
yesh and simran are handling this issue.

**Comment by SIMRAN1** [comment]
renamed classes and variable according to naming convention in my module
